[project]
name = "genai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ddgs>=9.14.4",
    "faiss-cpu>=1.14.3",
    "grandalf>=0.8",
    "langchain>=1.3.14",
    "langchain-chroma>=1.1.0",
    "langchain-cohere>=0.6.0",
    "langchain-community>=0.4.2",
    "langchain-experimental>=0.4.2",
    "langchain-google-genai>=4.3.1",
    "langchain-huggingface>=1.2.2",
    "langchain-openai>=1.4.0",
    "langchain-opentutorial>=0.0.9",
    "langchian>=0.2.5",
    "langgraph-checkpoint-sqlite>=3.1.0",
    "prompt-inspector-ux>=0.1.4",
    "pydantic[email]>=2.13.4",
    "rank-bm25>=0.2.2",
    "scikit-learn>=1.9.0",
    "sentence-transformers>=5.6.0",
    "streamlit>=1.60.0",
    "tiktoken>=0.13.0",
    "torch>=2.13.0",
    "torchvision>=0.28.0",
    "transformers>=5.14.1",
    "unstructured[all-docs]>=0.25.2",
    "youtube-transcript-api>=1.2.4",
]
